name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: keshavgarg070306-png
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          filename: github-metrics.svg
          
          # Plugin: Languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          # Plugin: Habits (Coding habits)
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          
          # Plugin: Pagespeed (Web Auditing)
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://keshavgarg-portfolio.vercel.app
          plugin_pagespeed_detailed: yes
